name: poc_cicd
description: "poc ci cd."
version: 0.0.6
homepage: https://github.com/GJS2162/poc-cicd
repository: https://github.com/GJS2162/poc-cicd

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
  # To add custom fonts to your application, add a fonts section here,
  # like this:

  # To add custom fonts to your application, add a fonts section here,